steps:
  - label: ":bash: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**

  - label: ":sparkles: Stable linting"
    plugins:
      - plugin-linter#v3.3.0:
          id: plugin-linter

  - label: ":bash: Tests"
    plugins:
      - plugin-tester#v1.1.1: ~

  - wait
  
  - label: ":sparkles: Self-test"
    plugins:
      - $BUILDKITE_REPO#$BUILDKITE_COMMIT:
          id: plugin-linter
