steps:
  - label: ":sparkles: Lint"
    plugins:
      $BUILDKITE_REPO#$BUILDKITE_COMMIT:
        id: plugin-linter

  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files: hooks/**

  - label: ":bash: Tests"
    plugins:
      docker-compose#v4.11.0:
        run: tests
