steps:
  - label: ":bash: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files: hooks/**

  - label: ":sparkles: Stable linting"
    plugins:
      - plugin-linter#v3.3.0:
          id: plugin-linter

  - label: ":bash: Tests"
    plugins:
      - plugin-tester#v1.2.0: ~

  - label: "Security Scan"
    key: security_scan
    plugins:
      - secrets#v1.0.0:
          variables:
            GITHUB_TOKEN: GITHUB_TOKEN
      - ossf-scorecard#v1.0.1:
          github_token: $$GITHUB_TOKEN

  - wait: ~
  
  - label: ":sparkles: Self-test"
    plugins:
      - $BUILDKITE_REPO#$BUILDKITE_COMMIT:
          id: plugin-linter
