#!/bin/bash

set -euo pipefail

if [ -z "${BUILDKITE_PLUGIN_PLUGIN_LINTER_ID:-}" ]; then
    echo ':boom: Missing id parameter in plugin configuration'
    exit 1
fi

TAG=${BUILDKITE_PLUGIN_PLUGIN_LINTER_IMAGE_VERSION:-v2.1.0}

echo "--- :docker: Fetching buildkite/plugin-linter:${TAG}"

docker pull "buildkite/plugin-linter:${TAG}"

echo "+++ Linting"

args=(
  "-it"
  "--rm"
  "--volume" "$PWD:/plugin:ro"
  "--env"    "PLUGIN_ID=$BUILDKITE_PLUGIN_PLUGIN_LINTER_ID"
)

if [[ -n "${BUILDKITE_PLUGIN_PLUGIN_LINTER_README:-}" ]] ; then
  args+=("--env" "PLUGIN_README=$BUILDKITE_PLUGIN_PLUGIN_LINTER_README")
fi

if [[ -n "${BUILDKITE_PLUGIN_PLUGIN_LINTER_SKIP_INVALID:-}" ]] ; then
  args+=("--env" "PLUGIN_SKIP_INVALID=$BUILDKITE_PLUGIN_PLUGIN_LINTER_SKIP_INVALID")
fi

docker run "${args[@]}" buildkite/plugin-linter:"${TAG}"
